"""autogenerate latest changes

Revision ID: 9f567179c926
Revises: 451c16e53e23
Create Date: 2023-10-12 08:44:25.094183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f567179c926'
down_revision: Union[str, None] = '451c16e53e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('label_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('label_confidence', sa.Integer(), nullable=False),
    sa.Column('detected_conditions', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('special_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['special_id'], ['users.special_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
